tap "mczachurski/wallpapper"
brew "act"
brew "aom"
brew "asdf"
brew "openssl@1.1"
brew "python@3.11"
brew "autojump"
brew "awscli"
brew "bat"
brew "cairo"
brew "harfbuzz"
brew "bfg"
brew "cloc"
brew "cmake"
brew "cocoapods"
brew "coreutils"
brew "curl"
brew "docutils"
brew "libevent"
brew "folly"
brew "fizz"
brew "wangle"
brew "fbthrift"
brew "fb303"
brew "edencommon"
brew "eza"
brew "fastlane"
brew "ffmpeg"
brew "gcc"
brew "open-mpi"
brew "flyctl"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "gnutls"
brew "gpgme"
brew "hdf5"
brew "htop"
brew "httpie"
brew "hub"
brew "shared-mime-info"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "libgsf"
brew "libimobiledevice"
brew "libmatio"
brew "libpq"
brew "librsvg"
brew "localtunnel"
brew "mackup"
brew "mas"
brew "nano"
brew "molten-vk"
brew "mozjpeg"
brew "ollama"
brew "openslide"
brew "poppler"
brew "postgresql@15"
brew "protobuf"
brew "pure"
brew "python@3.10"
brew "redis"
brew "ripgrep"
brew "rust"
brew "scc"
brew "spoof-mac"
brew "telnet"
brew "tldr"
brew "tree"
brew "vips"
brew "vulkan-loader"
brew "watch"
brew "watchman"
brew "wget"
brew "mczachurski/wallpapper/wallpapper"
cask "arc"
cask "beeper"
cask "brave-browser"
cask "chatgpt"
cask "claude"
cask "claude-code"
cask "cursor"
cask "docker-desktop"
cask "firefox"
cask "font-cascadia-code"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "font-meslo-lg-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "multipass"
cask "ngrok"
cask "notion"
cask "postman"
cask "visual-studio-code"
cask "warp"
cask "1password"
cask "adobe-creative-cloud"
cask "alfred"
cask "blender"
cask "cleanshot"
cask "cyberduck"
cask "daisydisk"
cask "discord"
cask "dropbox"
cask "expo-orbit"
cask "figma"
cask "istat-menus"
cask "obsidian"
cask "pgadmin4"
cask "raycast"
cask "rectangle"
cask "signal"
cask "slack"
cask "spotify"
cask "vlc"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "Draw Things", id: 6444050820
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Prime Video", id: 545519333
mas "SiteSucker", id: 442168834
# mas "TestFlight", id: 899247664  # Cannot install via mas - macOS security restrictions. Install manually from App Store.
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "WhatsApp", id: 310633997
mas "Windows App", id: 1295203466
mas "Xcode", id: 497799835
vscode "anthropic.claude-code"
vscode "bourhaouta.tailwindshades"
vscode "bradlc.vscode-tailwindcss"
vscode "codesandbox-io.codesandbox-projects"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.typescript-notebook"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "equinusocio.vsc-material-theme"
vscode "equinusocio.vsc-material-theme-icons"
vscode "esbenp.prettier-vscode"
vscode "expo.vscode-expo-theme"
vscode "firsttris.vscode-jest-runner"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "gruntfuggly.todo-tree"
vscode "heybourn.headwind"
vscode "jakebecker.elixir-ls"
vscode "jvitor83.types-autoinstaller"
vscode "mike-co.import-sorter"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.azure-account"
vscode "ms-vscode.remote-explorer"
vscode "ms-vsliveshare.vsliveshare"
vscode "nrwl.angular-console"
vscode "pantajoe.vscode-elixir-credo"
vscode "piersdeseilligny.betterfountain"
vscode "prisma.prisma"
vscode "redhat.vscode-yaml"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "teamsdevapp.ms-teams-vscode-extension"
vscode "unifiedjs.vscode-mdx"
vscode "xyc.vscode-mdx-preview"
vscode "yzhang.markdown-all-in-one"
